dist: trusty

sudo: false

language: node_js

node_js:
 - 6.11.5 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  # bundler: true
  # directories:
  #   - node_modules # NPM packages
  # TODO: Use npm once functions runtime is updated to a node verion with lock files
  yarn: true

install:
  - yarn install
  # TODO: Use npm i -g once functions runtime is updated to a node verion with lock files
  - npm i -g firebase-ci # install firebase-ci for use in creating config and deploying

script:
  - firebase-ci createConfig # create env specific src/config.js
  - npm run lint
  # - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  # deploy hosting, RTDB rules, firestore rules, functions, and
  # functions config (from mapEnv settings in .firebaserc)
  - firebase-ci deploy
