dist: trusty

sudo: false

language: node_js

node_js:
 - 6.11.5 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod
    - test

cache:
  # bundler: true
  directories:
    - node_modules # NPM packages
  # TODO: Use npm once functions runtime is updated to a node verion with lock files
  yarn: true

install:
  - yarn install
  - yarn add firebase-ci@alpha

script:
  # create env specific src/config.js
  - firebase-ci createConfig
  - npm run lint
  # - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  # Use firebase-ci to deploy hosting, RTDB rules, firestore rules, functions,
  # and functions config (from mapEnv settings in .firebaserc)
  - firebase-ci deploy
